new horizontal-card component added
thedevdojo/tails-components pull request #169
Opened 2020-10-04 07:27 UTC by AkshatSidharth

Hey, I have tried once again, this time I have added a new horizontal-card component comprising of tailwind css.

2020-10-04 07:35 UTC, AkshatSidharth commented
I am new to this open source fraternity, and I am trying my level best to learn new things.

2020-10-04 07:36 UTC, thinkverse requested changes
Thank you for contributing to Tails. I suggest you work a bit on the presentation of your component.
This is how it shows when I load it up in Tails currently. Remember, this is how the end-user will view it on Tails if they want to edit it. 🙂

![Screen shot of component on Tails](https://user-images.githubusercontent.com/2221746/95009772-d6f67f00-0624-11eb-9473-3d3ce01c980c.png)

2020-10-04 07:36 UTC, thinkverse commented on components/horizontal-card.html
> +        <img class="w-10 h-10 rounded-full mr-4" src="/img/jonathan.jpg" alt="Avatar of Jonathan Reinink">
No image, I suggest using something like [Unsplash] or, grab one of the avatars we already use in Tails.

```suggestion
        <img class="w-10 h-10 rounded-full mr-4" src="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&faces=1&faceindex=1&facepad=2.5&w=500&h=500&q=80" alt="Avatar of Jonathan Reinink">
```

[unsplash]: https://unsplash.com/

2020-10-04 07:36 UTC, thinkverse commented on components/horizontal-card.html
> +    <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url('/img/card-left.jpg')" title="Woman holdin
Same issue here, no image is being loaded since the images are relative to your system. I suggest switching to something from [Unsplash].

[unsplash]: https://unsplash.com/

2020-10-04 07:38 UTC, AkshatSidharth commented on components/horizontal-card.html
> +    <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url('/img/card-left.jpg')" title="Woman holdin
I will surely change and update it. Thanks a lot for your guidance.

2020-10-04 08:09 UTC, AkshatSidharth commented
Dear Sir, I have made the required updates.

2020-10-04 08:09 UTC, AkshatSidharth commented on components/horizontal-card.html
> +    <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url('/img/card-left.jpg')" title="Woman holdin
Dear Sir, I have made the required updates

2020-10-05 17:00 UTC, AkshatSidharth commented on components/horizontal-card.html
> +    <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url('/img/card-left.jpg')" title="Woman holdin
I have made the necessary changes.

2020-10-06 04:35 UTC, AkshatSidharth commented
Please look into it sir.

2020-10-30 10:29 UTC, bobbyiliev commented
The image still does not seem to be loading:

![image](https://user-images.githubusercontent.com/21223421/97694581-7a637400-1aab-11eb-9f86-b823931df416.png)

Thank you for your contribution, but unfortunately, we have decided not to merge this PR as there are already multiple user card components.

2020-10-30 10:29 UTC, closed without merging