ADDING NEW FEATURE COMPMNENT
thedevdojo/tails-components pull request #25
Opened 2020-09-25 05:07 UTC by mrmayank2710

hey there im adding new feature component

2020-09-25 11:23 UTC, thinkverse requested changes

2020-09-25 11:23 UTC, thinkverse commented on components/feature-task.html
> +        <img src="C:\Users\Mayank\Desktop\PYTHON PRO\mockvita\tails\README.md\Vice-City-1920x1080.png"
The use of copyrighted trademarks isn't a good idea, better to use something like [Unsplash]. Also, the path is absolute based on your system. If you want to include an image, browse around Unsplash, they have a great selection of free images to use. 👍

[unsplash]: https://unsplash.com/

2020-09-25 11:23 UTC, thinkverse commented on components/feature-task.html
> +<div class="bg-black relative min-h-screen min-w-screen">
The pure black is to harch for background colors, which paired with the color choice for the `h2` on line 11, results in horrible contrast not even hitting the [WCAG A] standard.

[wcag a]: https://webaim.org/resources/contrastchecker/

2020-09-25 11:23 UTC, thinkverse commented on components/feature-task.html
> +            <p class="text-gray-600 text-base mt-5">Are you ready for GAMING TOURNAMENTS!!!!!!!!!!!!!!!!!!!!!!!!!!!</p>
To many exclamation marks. 🙂
```suggestion
            <p class="text-gray-600 text-base mt-5">Are you ready for GAMING TOURNAMENTS!</p>
```

2020-09-25 16:33 UTC, tnylea commented
@mrmayank2710 Yeah, if you could replace this image with an image from unspash and give it an absolute URL, then I can see about getting this one merged in.

I may do a few touch-ups as well, just so that way it doesn't look like the other featured blocks :)

Thanks!

2020-09-26 04:36 UTC, mrmayank2710 commented on components/feature-task.html
> +<div class="bg-black relative min-h-screen min-w-screen">
okay i will change the background color.

2020-09-26 04:36 UTC, mrmayank2710 commented on components/feature-task.html
> +            <p class="text-gray-600 text-base mt-5">Are you ready for GAMING TOURNAMENTS!!!!!!!!!!!!!!!!!!!!!!!!!!!</p>
im will remove them too ! sry!

2020-09-26 04:55 UTC, closed without merging