Adding new testimonial component
thedevdojo/tails-components pull request #27
Opened 2020-09-25 06:01 UTC by SanjeebNath382

Hey thanks for great youtube video, i am adding a new testimonial component

2020-09-25 11:32 UTC, thinkverse requested changes
A better name for this file would be `testimonial-single.html` since it's a single testimonial.

2020-09-25 11:32 UTC, thinkverse commented on components/testimonial-sanjeeb.html
> +      <p class="leading-relaxed text-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lorem ex, pretium non sodales at, feugiat eget magna. Morbi quis rhoncus leo, in semper metu
A more realistic testimonial than a lorem ipsum dump would demonstrate the component better. 🙂

2020-09-26 07:49 UTC, tnylea commented
Thanks man 🙌 Will get this one merged in, in the morning 😊

2020-09-26 07:51 UTC, SanjeebNath382 commented
thanks man!

2020-09-26 09:11 UTC, thinkverse approved these changes

2020-09-26 09:14 UTC, merged