Adding new product list component
thedevdojo/tails-components pull request #297
Opened 2021-10-01 17:40 UTC by KaranBajaj594

Hello, 

 Adding a new component called product list.

2021-10-01 17:48 UTC, thinkverse requested changes
Thank you for contributing to Tails. I like the component, but it could use some improvements. 🙂

2021-10-01 17:48 UTC, thinkverse commented on components/product-list.html
> +            <img src="https://5.imimg.com/data5/YX/OO/TA/ANDROID-108727015/product-jpeg-500x500.jpg" alt="Men Navy-blue Tshirt#9087" class="w-full h-full object-center object-cover lg:w-full lg:h-ful
It would be better if the images came from a service like Unsplash or something similar.

2021-10-01 17:48 UTC, thinkverse commented on components/product-list.html
> +              </div>
```suggestion
              <p class="mt-1 text-sm text-gray-500">Navy Blue</p>
              <p class=" mt-1 text-sm font-medium text-gray-900">$25</p>
```

The extra `<div>` tags aren't necessary, the paragraph tags are enough.

2021-10-01 17:48 UTC, thinkverse commented on components/product-list.html
> +      <h2 class="text-2xl text-gray-900 font-extrabold tracking-tight ">Product-List</h2>
```suggestion
      <h2 class="text-2xl text-gray-900 font-extrabold tracking-tight ">Product List</h2>
```
There is  no need to add a dash `-` between the words, if your could you can remove them all. 🙂

2021-10-01 17:52 UTC, KaranBajaj594 commented on components/product-list.html
> +              </div>
Ok . Thank you for suggestion. I will work on it

2021-10-01 17:52 UTC, KaranBajaj594 commented on components/product-list.html
> +            <img src="https://5.imimg.com/data5/YX/OO/TA/ANDROID-108727015/product-jpeg-500x500.jpg" alt="Men Navy-blue Tshirt#9087" class="w-full h-full object-center object-cover lg:w-full lg:h-ful
ok..

2021-10-01 17:54 UTC, KaranBajaj594 commented on components/product-list.html
> +      <h2 class="text-2xl text-gray-900 font-extrabold tracking-tight ">Product-List</h2>
Ok .I will change it

2021-10-01 19:19 UTC, KaranBajaj594 commented
I worked on your suggestions. and made the changes

2021-10-01 19:21 UTC, KaranBajaj594 commented
I commited my modified version but not finding the way to give you another pull request.Can you please help me with this?

2021-10-01 19:23 UTC, thinkverse commented
> I commited my modified version but not finding the way to give you another pull request.Can you please help me with this?

The commit you've made to your forked version will all be added automatically to this PR.

2021-10-01 19:25 UTC, KaranBajaj594 commented
Ok that means you can now check my changes.?

2021-10-01 19:27 UTC, thinkverse requested changes
Please clean up this PR. It contains 3 unnecessary files `s=bg-white`, `s=group relative`, and `s=mt-6 grid grid-cols-1 gap-y-10 gap-x-6 smgrid-cols-2 lggrid-cols-4 xlgap-x-8` which was added in the 013e0599aaac6d183c624d07a24412ab8a6ee136 commit.

2021-10-01 19:40 UTC, KaranBajaj594 commented
Deleted the files

2021-10-01 19:42 UTC, KaranBajaj594 commented
Deleted the files..Can you please check now

On Sat, Oct 2, 2021, 12:57 AM Kim Hallberg ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please clean up this PR. It contains 3 unnecessary files s=bg-white, s=group
> relative, and s=mt-6 grid grid-cols-1 gap-y-10 gap-x-6 smgrid-cols-2
> lggrid-cols-4 xlgap-x-8 which was added in the 013e059
> <https://github.com/thedevdojo/tails/commit/013e0599aaac6d183c624d07a24412ab8a6ee136>
> commit.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/thedevdojo/tails/pull/297#pullrequestreview-769310815>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATFAIBG6EE5O6YP7UBYNHETUEYDTLANCNFSM5FFFR56Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-02 04:41 UTC, KaranBajaj594 commented
Hello
I didn't got your response. Do you want any more modification?
Are you happy with my component? i

2021-10-02 06:06 UTC, KaranBajaj594 commented
Can you please response if you liked the component or not or if you want
any more modification?....

If you liked it...can you please merge it?

On Sat, Oct 2, 2021, 1:12 AM Karan Bajaj ***@***.***> wrote:

>
>
> Deleted the files..Can you please check now
>
> On Sat, Oct 2, 2021, 12:57 AM Kim Hallberg ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Please clean up this PR. It contains 3 unnecessary files s=bg-white, s=group
>> relative, and s=mt-6 grid grid-cols-1 gap-y-10 gap-x-6 smgrid-cols-2
>> lggrid-cols-4 xlgap-x-8 which was added in the 013e059
>> <https://github.com/thedevdojo/tails/commit/013e0599aaac6d183c624d07a24412ab8a6ee136>
>> commit.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/thedevdojo/tails/pull/297#pullrequestreview-769310815>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATFAIBG6EE5O6YP7UBYNHETUEYDTLANCNFSM5FFFR56Q>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-10-02 10:24 UTC, thinkverse approved these changes
Looks good. 👍

2021-10-02 10:25 UTC, merged

2021-10-02 11:06 UTC, KaranBajaj594 commented
Thank you so much....it was a pleasure working with you....


On Sat, Oct 2, 2021, 3:56 PM Kim Hallberg ***@***.***> wrote:

> Merged #297 <https://github.com/thedevdojo/tails/pull/297> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/thedevdojo/tails/pull/297#event-5398007606>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATFAIBDPX4P2TFBANSUJOXTUE3M37ANCNFSM5FFFR56Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>