Added business card component
thedevdojo/tails-components pull request #330
Opened 2021-10-08 13:21 UTC by shiladityab24

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Description
Added business card component which will be compatible for all the browsers.

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
![Desktop-View](https://drive.google.com/uc?export=view&id=1E2CyYHZDAkg-JBvwcod_XxqTsFpohCyZ)

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
![Happy](https://media.giphy.com/media/TdfyKrN7HGTIY/giphy.gif)

2021-10-12 08:06 UTC, bobbyiliev requested changes
Hi there! Thank you for this PR! This looks great! Just a couple of suggestions:
- Could you remove the extra white spaces so that the document is formatted well
- I think it would be nice if we set the background color to match the other components, that way it would be consistent with the rest of the components, we could go for `bg-gray-100` for example

Thank you!

2021-10-12 08:07 UTC, bobbyiliev commented on components/business-card.html
> +              >
Also one last thing, maybe move the classes on the same line as the elements throughout the document

2021-10-14 13:22 UTC, shiladityab24 commented on components/business-card.html
> +              >
Understood.

2021-10-14 14:26 UTC, shiladityab24 commented
Hey @bobbyiliev I have updated the business card component as per your suggested changes.

2021-10-15 05:56 UTC, bobbyiliev approved these changes
Thank you for this contribution!

2021-10-15 05:57 UTC, merged