Adding new product card component
thedevdojo/tails-components pull request #338
Opened 2021-10-16 05:15 UTC by thenose-samuel

Hello, I'm adding a new component called product card

2021-10-16 10:33 UTC, bobbyiliev requested changes

2021-10-16 10:33 UTC, bobbyiliev commented on components/product-card.html
> +        <img class="object-cover cursor-pointer rounded-t-md" src="https://cdn.pixabay.com/photo/2016/02/29/00/19/cake-1227842_1280.jpg" alt="product-image" />
Thank you for the PR! A few remarks:

Can you change the image with an image from https://unsplash.com/?

2021-10-16 10:33 UTC, bobbyiliev commented on components/product-card.html
> +          </svg>
There seem to be extra spaces on each line. Could you adjust that so that the formatting is consistent? Thank you!

2021-10-16 11:45 UTC, thenose-samuel commented on components/product-card.html
> +        <img class="object-cover cursor-pointer rounded-t-md" src="https://cdn.pixabay.com/photo/2016/02/29/00/19/cake-1227842_1280.jpg" alt="product-image" />
Thanks for the review. Yes I shall make the change

2021-10-16 11:45 UTC, thenose-samuel commented on components/product-card.html
> +          </svg>
Sure I will do that

2021-10-17 05:21 UTC, bobbyiliev approved these changes

2021-10-17 05:22 UTC, merged