Adding new home component
thedevdojo/tails-components pull request #343
Opened 2021-10-17 05:23 UTC by wdhenarangoda

Hey devdojo,

I'm adding a new component called 'build home'. Please accept it.
Thank you!

2021-10-17 05:35 UTC, bobbyiliev requested changes
Looks great! Just a couple of remarks:

2021-10-17 05:35 UTC, bobbyiliev commented on components/build-home.html
> +              <img src="https://assets-news.housing.com/news/wp-content/uploads/2020/11/24190402/What-is-an-immovable-property-FB-1200x700-compressed.jpg" class="">
Would you mind changing the image with an image from https://unsplash.com/?

2021-10-17 05:35 UTC, bobbyiliev commented on components/build-home.html
> +  </section>
It looks like that there are some extra spaces throughout the file, would you mind formatting it?

2021-10-17 05:54 UTC, wdhenarangoda commented on components/build-home.html
> +  </section>
Done!

2021-10-17 05:54 UTC, wdhenarangoda commented on components/build-home.html
> +              <img src="https://assets-news.housing.com/news/wp-content/uploads/2020/11/24190402/What-is-an-immovable-property-FB-1200x700-compressed.jpg" class="">
Done!

2021-10-17 05:58 UTC, wdhenarangoda commented on components/build-home.html
> +  </section>
Please accept my pull request.

2021-10-17 05:58 UTC, wdhenarangoda commented on components/build-home.html
> +              <img src="https://assets-news.housing.com/news/wp-content/uploads/2020/11/24190402/What-is-an-immovable-property-FB-1200x700-compressed.jpg" class="">
Please accept my pull request.

2021-10-18 11:49 UTC, bobbyiliev approved these changes

2021-10-18 11:49 UTC, merged