Create project-gallery.html
thedevdojo/tails-components pull request #346
Opened 2021-10-20 02:14 UTC by GoldinGuy

Add project gallery component for Hacktoberfest!

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Added new project gallery component

## Related Tickets & Documents

N/A

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

![image](https://user-images.githubusercontent.com/47064842/138016644-07150fc8-4daa-4896-a0c7-11e78622a4d1.png)

## Added to documentation?

- [ ] 📜 readme
- [X] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

[link](https://tenor.com/view/hollow-knight-hollow-dance-the-hollow-gif-17512843)

2021-10-20 06:30 UTC, bobbyiliev requested changes

2021-10-20 06:30 UTC, bobbyiliev commented on components/project-gallery.html
> +  <section class="bg-teal-50" id="projects">
Looks good! There are just some extra whitespace throughout the file, would you mind formatting the document and removing them?

2021-10-20 06:30 UTC, bobbyiliev commented on components/project-gallery.html
> +            >
One more small remark, can you put the classes on the same line as the tags? Thanks 🙌

2021-10-20 16:01 UTC, GoldinGuy commented on components/project-gallery.html
> +  <section class="bg-teal-50" id="projects">
Will do

2021-10-20 16:01 UTC, GoldinGuy commented on components/project-gallery.html
> +            >
Sure thing!

2021-10-20 16:05 UTC, GoldinGuy commented
Requested changes have been made. Let me know if anything else needs work

2021-10-21 06:01 UTC, bobbyiliev approved these changes

2021-10-21 06:02 UTC, merged