Pricing selector component
thedevdojo/tails-components pull request #35
Opened 2020-09-25 13:15 UTC by ThinkDevStudios

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Tiered Pricing Selector

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
![image](https://user-images.githubusercontent.com/2109352/94271344-16153800-ff74-11ea-9209-691fec706254.png)
![image](https://user-images.githubusercontent.com/2109352/94271373-20cfcd00-ff74-11ea-98fd-ad105e076707.png)
![Screen Shot 2020-09-25 at 9 14 00 PM](https://user-images.githubusercontent.com/2109352/94271389-25948100-ff74-11ea-975c-e8ad816a8bd3.png)

## Added to documentation?

- [ ] 📜 readme
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2020-09-25 14:57 UTC, thinkverse requested changes
I'm pretty sure the icons are placed in the wrong place? 🤔&nbsp; The blue seems like the selected package but doesn't have the green checked icon.

I'm not sold on the packages being `div` elements, there's no way to "select" them. I would suggest looking if there's a way we can make them selectable maybe. 🤔

The quantity options seem redundant to me since you're asking the end-user to select _a_ package, not packages. 👍

2020-09-25 14:57 UTC, thinkverse commented on components/pricing-select.html
> +<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
This isn't necessary since TailwindCSS is included in the `/tails` site, and it's assumed the end-user already has TailwindCSS added to their site. 🙂
```suggestion
```

2020-09-25 14:57 UTC, thinkverse commented on components/pricing-select.html
> +    <div class="container w-full px-10 mx-auto xl:w-1/2 sm:px-5">
I would remove the `xl:w-1/2`, component looks fine without it.
```suggestion
    <div class="container w-full px-10 mx-auto sm:px-5">
```

2020-09-25 17:04 UTC, ThinkDevStudios commented
>
> I'm pretty sure the icons are placed in the wrong place? 🤔  The blue
> seems like the selected package but doesn't have the green checked icon.

At first, I was thinking of the blue was the suggested / best value
package. But your right it might be confusing for some user. Will change it
right away. Thank you!

As for the packages, it was meant to act as a toggle only, to show or hide
package details with buttons linked to the specific package checkout.

I was thinking of using Alpine js to make the component interactive.

*Roville Sarate*
Co-Founder, CTO



On Fri, Sep 25, 2020 at 10:57 PM Kim Hallberg <notifications@github.com>
wrote:

> *@thinkverse* requested changes on this pull request.
>
> I'm pretty sure the icons are placed in the wrong place? 🤔  The blue
> seems like the selected package but doesn't have the green checked icon.
>
> I'm not sold on the packages being div elements, there's no way to
> "select" them. I would suggest looking if there's a way we can make them
> selectable maybe. 🤔
>
> The quantity options seem redundant to me since you're asking the end-user
> to select *a* package, not packages. 👍
> ------------------------------
>
> In components/pricing-select.html
> <https://github.com/thedevdojo/tails/pull/35#discussion_r495038219>:
>
> > @@ -0,0 +1,101 @@
>
> +<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
>
>
> This isn't necessary since TailwindCSS is included in the /tails site,
> and it's assumed the end-user already has TailwindCSS added to their site.
> 🙂
> ⬇️ Suggested change
>
> -<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
>
>
> ------------------------------
>
> In components/pricing-select.html
> <https://github.com/thedevdojo/tails/pull/35#discussion_r495045561>:
>
> > @@ -0,0 +1,101 @@
>
> +<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
>
> +<section class="relative min-h-screen py-16 bg-gray-200 min-w-screen animation-fade animation-delay">
>
> +    <div class="container w-full px-10 mx-auto xl:w-1/2 sm:px-5">
>
>
> I would remove the xl:w-1/2, component looks fine without it.
> ⬇️ Suggested change
>
> -    <div class="container w-full px-10 mx-auto xl:w-1/2 sm:px-5">
>
> +    <div class="container w-full px-10 mx-auto sm:px-5">
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/thedevdojo/tails/pull/35#pullrequestreview-496490016>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQC7KGR465KESS7R5GY62DSHSVVVANCNFSM4RZRBZBA>
> .
>

2020-09-25 17:51 UTC, thinkverse commented
Hmm, I'm personally not sure if Tails support Alpine out-the-box, or even if it should. It seems for some TailwindCSS and Alpine work great together. Let's ping @tnylea and see what he says about it. 🙂

2020-09-25 19:16 UTC, merged

2020-09-26 04:09 UTC, ThinkDevStudios commented
Hi! Was this PR merged? cant seem to find it on the thedevdojo:master branch

2020-09-26 04:21 UTC, ThinkDevStudios commented
I think I might have deleted this file from the featured content tiles that why its no longer showing from the master. after merging the featured content tiles to thedevdojo:master.

2020-10-01 06:28 UTC, ThinkDevStudios commented
Hi tnylea. Have not received hacktoberfest pull request yet. Or do i need to submit another pull request =(?