Added Registration Form Tailwind CSS Component
thedevdojo/tails-components pull request #37
Opened 2020-09-25 14:12 UTC by ryuk156

## What type of PR is this? (check all applicable)
Hi There. Adding a Registration Form Component. 

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
![image](https://user-images.githubusercontent.com/49101492/94277284-fdeaec00-ff66-11ea-8b96-d68228168f2c.png)

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2020-09-25 14:15 UTC, ryuk156 commented
@thinkverse  please review

2020-09-25 14:40 UTC, thinkverse requested changes
Personally, I would remove the `select` and `checkboxes` sections. These components are plug and play, so those sections won't be used out-of-the-box. 🙂&nbsp; As for the filename, I would rename it to match the component more like `registration-form-full.html` since this seems like a registration form that is a full-fledge one and not one with just _name_, _email_ and _password_. 🤔

I would also work on the spacing a bit more, some groups have their inputs and labels to close so there isn't unified spacing between all elements. 👍

Pssh, you're missing the password input by the way. 🤫

Good first pass though, I would keep working on it some more. Maybe look at [dribbble] or some UI/UX sites for inspiration. 😀

[dribbble]: https://dribbble.com

2020-09-25 14:40 UTC, thinkverse commented on components/Registration-form.html
> +          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id=
Placeholder email doesn't match the placeholder's firstname and lastname.
```suggestion
          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-email" type="email" placeholder="janedoe@example.com">
```

2020-09-25 14:40 UTC, thinkverse commented on components/Registration-form.html
> +            Number
Think that should be `phone number` and not `number`, it's best to be specific. 👍

2020-09-25 14:40 UTC, thinkverse commented on components/Registration-form.html
> +          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id=
Best to not use `type[number]` for inputting phone numbers, that will add an increment/decrement style input in most browsers (see screenshot). Stick with `type[tel]` for telephone number, default to regular `text` in unsupported browsers so there won't be an issue with it. 🙂
```suggestion
          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-email" type="tel" placeholder="+91 XXX XXX XXXX">
```

![Screen shot showing default increment input](https://user-images.githubusercontent.com/2221746/94279778-e141ba80-ff4c-11ea-8385-feff51ef3c75.gif)

2020-09-25 14:49 UTC, ryuk156 commented on components/Registration-form.html
> +          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id=
Will make changes in small time thank you for review

2020-09-25 14:58 UTC, ryuk156 commented
![image](https://user-images.githubusercontent.com/49101492/94282569-98e6c480-ff6d-11ea-9e03-e7d0e55621f5.png)

@thinkverse  Done

2020-09-27 03:13 UTC, merged

2020-09-27 03:17 UTC, tnylea commented
Thanks, @ryuk156, went ahead and merged this one in, I've made a few UI tweaks and I've renamed it to `form-registration-long.html`.

Thanks for the contribution 🙌

2020-09-27 03:46 UTC, ryuk156 commented
👍😇