Adding information modal
thedevdojo/tails-components pull request #49
Opened 2020-09-27 06:32 UTC by crisgarlez

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Added an information modal with a close button

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

![Captura](https://user-images.githubusercontent.com/5332140/94357706-c2cce380-0060-11eb-9e21-ebd9688c014f.PNG)

## [optional] What gif best describes this PR or how it makes you feel?

![tenor](https://user-images.githubusercontent.com/5332140/94357761-2c4cf200-0061-11eb-8e44-f5ee578081f4.gif)

2020-09-27 13:35 UTC, thinkverse requested changes
Thank you for your contribution to Tails. 😀&nbsp; I like the component but, there are some little changes I would suggest though. 🙂

2020-09-27 13:35 UTC, thinkverse commented on components/information-modal.html
> +                <svg class="w-6 h-6 text-white fill-current text-blue-500" viewBox="0 0 40 40"
Don't think this text color will be necessary since you have the blue one overwriting it.

```suggestion
                <svg class="w-6 h-6 fill-current text-blue-500" viewBox="0 0 40 40"
```

2020-09-27 13:35 UTC, thinkverse commented on components/information-modal.html
> +        <div class="flex border-b border-gray-100 px-5 py-4">
Just to make the border a little bit more visible to the eye.

```suggestion
        <div class="flex border-b border-gray-200 px-5 py-4">
```

2020-09-27 13:35 UTC, thinkverse commented on components/information-modal.html
> +        <div class="px-5 py-4 flex justify-end">
Maybe another background for the footer section just to show the distinction of separate sections.

```suggestion
        <div class="bg-gray-100 border-t border-gray-300 px-5 py-4 flex justify-end">
```

2020-09-27 18:08 UTC, crisgarlez commented
Modal looks little better now  😀

![Captura2](https://user-images.githubusercontent.com/5332140/94372370-774b2180-00c2-11eb-8dfb-9a36f4be609f.PNG)

2020-09-27 18:28 UTC, thinkverse approved these changes
I like the changes. 🙂&nbsp; Throwing the final decision to @tnylea, he'll have some input on the filename I think. 👍

2020-09-30 16:20 UTC, thinkverse commented
Didn't get any update on the filename so I'm merging this. 👍

2020-09-30 16:20 UTC, merged