add form-login-dark.html
thedevdojo/tails-components pull request #57
Opened 2020-09-30 16:25 UTC by aksharsramesh

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [✓] 🚩 Other

## Description
Added a dark mode sign in page

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

## Added to documentation?

- [ ] 📜 readme
- [✓] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2020-09-30 16:31 UTC, thinkverse commented on components/form-login-dark.html
> +                    <a class="block text-sm text-indigo-200 fontme hover:underline" href="#">Forgot your password?</a>
Unused CSS class, best to remove it. 👍

```suggestion
                    <a class="block text-sm text-indigo-200 hover:underline" href="#">Forgot your password?</a>
```

2020-09-30 16:33 UTC, thinkverse requested changes
Thank you for contributing to Tails. 🙂

Love the color choice for a dark version. 👍

2020-09-30 16:33 UTC, thinkverse commented on components/form-login-dark.html
> +                <button type="submit" class="w-full px-4 py-2 text-sm text-center text-white bg-indigo-500 rounded-md hover:bg-indigo-500">Sign in</button>
No hover effect on the button since the background color has been set to the same color.

```suggestion
                <button type="submit" class="w-full px-4 py-2 text-sm text-center text-white bg-indigo-500 rounded-md hover:bg-indigo-700">Sign in</button>
```

2020-09-30 16:51 UTC, aksharsramesh commented
@thinkverse Do you have any more suggestions

2020-09-30 19:45 UTC, thinkverse requested changes
The input elements could be a bit darker to more fit the style of a dark-mode variant. 👍

2020-10-02 21:08 UTC, thinkverse approved these changes
Sorry for the late response, been swamped. I'll merge this and add some changes to it later. 🙂

2020-10-02 21:08 UTC, merged