newletter component
thedevdojo/tails-components pull request #59
Opened 2020-09-30 18:40 UTC by pranav2012

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2020-09-30 19:26 UTC, bobbyiliev requested changes
Overall this looks good, but note that the component needs to be written in [TailwindCSS](http://tailwindcss.com/), so we can't merge it as it is unless you rework it in TailwindCSS.

Thanks 🙌

2020-09-30 21:19 UTC, connecteev commented
@pranav2012 Also any chance you could attach some screenshots when this is redone in Tailwindcss only?

2020-09-30 21:32 UTC, pranav2012 commented
added

2020-10-01 08:13 UTC, pranav2012 commented
Hey @bobbyiliev @thinkverse Please review and merge added screenshots and Tailwood css and also removed the js . Thank you:smile:

2020-10-01 16:01 UTC, bobbyiliev commented on components/newsletter.html
> +    </div>
Looks good to me, just one change request on my side. Can you remove the body and the head tags? Only this div is enough 🙌

2020-10-01 16:03 UTC, pranav2012 commented on components/newsletter.html
> +    </div>
sure :+1:

2020-10-01 16:06 UTC, pranav2012 commented
@bobbyiliev done removed the tags

2020-10-01 17:00 UTC, tnylea requested changes
Very cool, if you could make this responsive, I can merge it in and then make a few touch-ups :)

Thanks!

![Screen Shot 2020-10-01 at 9 58 27 AM](https://user-images.githubusercontent.com/601261/94840163-db285f80-03cc-11eb-8731-e3ddb2aaf683.png)

![Screen Shot 2020-10-01 at 9 58 39 AM](https://user-images.githubusercontent.com/601261/94840170-de235000-03cc-11eb-8aae-16c09725825c.png)

2020-10-01 17:59 UTC, pranav2012 commented
@tnylea , made it responsive :smile:

2020-10-02 13:08 UTC, pranav2012 commented
@tnylea @bobbyiliev Review my pull request updated with all the requirement's mentioned, Thank you :blush:

2020-10-04 09:46 UTC, bobbyiliev approved these changes
Looks good

2020-10-04 09:50 UTC, merged

2020-10-04 10:04 UTC, pranav2012 commented
Thanks @bobbyiliev and everyone 😊