Adding a new footer component
thedevdojo/tails-components pull request #66
Opened 2020-09-30 20:01 UTC by SanjeebNath382

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

2020-09-30 20:14 UTC, thinkverse requested changes
Thank you for contributing to Tails again @SanjeebNath382 🙂

I would suggest wrapping the footer in a div and just pushing it to the bottom for presentational purposes, something like `<div class="bg-gray-100 flex w-full min-h-screen items-end">` and then adding a `w-full` to the footer itself to fill out the full width.

Also, some spacing on the links would be appreciated. They look a bit cramped.

Not 100% on the mobile view, there isn't enough space on the social icons, and the text isn't aligned correctly, I would spend some more times on the mobile view. 🙂

2020-09-30 20:14 UTC, thinkverse commented on components/footer-simple.html
> +  <div class="bg-red-200">
Not sure about the red color there, seems out of place for me.

2020-09-30 20:14 UTC, thinkverse commented on components/footer-simple.html
> +<footer class="text-gray-700 body-font">
Maybe just add an overall background to the whole footer instead?

```suggestion
<footer class="text-gray-700 bg-gray-400 body-font">
```

2020-09-30 21:18 UTC, connecteev commented
@SanjeebNath382 Any chance you could attach some screenshots?

2020-10-02 21:14 UTC, thinkverse commented
This PR now contains more than one component and none of the suggested changes has been implemented. Therefore I'm closing this PR and suggest you separate the component into separate PRs.

2020-10-02 21:14 UTC, closed without merging